title: UW-Madison Carpentries Community
logo: /assets/img/logo.png
description: Information on the University of Wisconsin - Madison's Carpentries Community
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
