title: UW-Madison Carpentries Community
logo: /assets/img/Data-Science-Hub-MASTER_digital-color-icon-only-w-more-border.png
description: Information on the University of Wisconsin - Madison's Carpentries Community
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
dshweb: https://hub.datascience.wisc.edu/
carpentries: https://carpentries.org/
